version: '3'

services:
  database:
    image: mysql:8.0.32
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: '!ChangeMe!'
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
